path: ../twm/data/KITTI/ # dataset root dir
train: images/train  # train images (relative to 'path') 4 images
val: images/val  # val images (relative to 'path') 4 images
test:  # test images (optional)

names:
  0: car
  1: cyclist
  2: pedestrian
  3: person_sitting
  4: truck
  5: van
  6: tram
  7: misc
 